name: Linting

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
    
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Setup and install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
          version: latest
      - name: Install step
        run: "pnpm install"
      - name: Lint files
        run: "pnpm run lint"